services:
  db: 
    image: postgres:16
    container_name: register-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cyco
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    networks:
      - register-network

  # api:
  #   build: .
  #   container_name: register-service
  #   environment:
  #     DATABASE_URL: "mysql://root:root@register-database:3306/cyco"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   networks:
  #     - register-network

networks:
  register-network:
    driver: bridge
