POST http://localhost:3000/waste-collectors
Content-Type: application/json

{
  "email": "enterprise22@gmail.com",
  "password": "12345678",
  "name": "Empresa de Coleta de Lixo 22",
  "isEnterprise": true,
  "materials": [
    "Glass"
  ],
   "phone": {
    "ddd": 11,
    "ddi": 55,
    "number": 961868645
  },
  "document": "58608125000173",
  "address": {
    "zipCode": "06449300"
  },
  "enterprise": {
    "companyName": "Coleta de Lixo Ltda",
    "commercialName": "Coleta de Lixo"
  }
}

### POST Pessoa fisica

POST http://localhost:3000/waste-collectors
Content-Type: application/json

{
  "email": "collector@gmail.com",
  "password": "12345678",
  "name": "Catador",
  "isEnterprise": false,
  "materials": [
    "Glass"
  ],
   "phone": {
    "ddd": 11,
    "ddi": 55,
    "number": 961868671
  },
  "document": "16543092068",
  "address": {
    "zipCode": "06449300"
  }
}

###
GET http://localhost:3000/waste-collectors

###
GET http://localhost:3000/waste-collectors/b6a59cbf-b0ba-45c2-90df-f48d92b93cc7

